/* =======================================================
   FILENAME: build.js
   LAST EDIT DATE: 2026-08-17 EST
   VERSION: 1.0.0

   PURPOSE:
       Inlines the shared header.html and footer.html markup
       directly into every top-level page, replacing the old
       runtime fetch()-based injection (js/header.js, js/footer.js).

   DESCRIPTION:
       header.html and footer.html remain the single source of
       truth for the site's navigation and footer. This script
       reads them and writes their markup into each page between
       generated marker comments, so pages render immediately
       with no extra network requests, no flash of missing nav,
       and no dependency on running through a local server
       (fetch() fails when a page is opened directly as a file).

   USAGE:
       Run this after editing header.html or footer.html:
           node build.js
       Re-running is safe — it replaces only the content between
       the HEADER/FOOTER marker comments in each page.

   DEPENDENCIES:
       - header.html, footer.html (source templates)
       - Every top-level *.html page except header.html/footer.html

   AUTHOR:
       Brian Von Wert / Rising Tide
======================================================= */

const fs = require("fs");
const path = require("path");

const ROOT = __dirname;

const PAGES = [
    "index.html",
    "about.html",
    "leadership.html",
    "events.html",
    "minutes.html",
    "support.html",
    "contact.html",
    "join.html",
    "bylaws.html",
    "code-of-conduct.html",
];

function extractTag(html, tagName) {
    // Strip HTML comments first so mentions of "<tag>...</tag>" inside a
    // documentation comment (e.g. describing what this function does)
    // can't be mistaken for the real markup below it.
    const withoutComments = html.replace(/<!--[\s\S]*?-->/g, "");
    const match = withoutComments.match(new RegExp(`<${tagName}[\\s\\S]*?</${tagName}>`));
    if (!match) {
        throw new Error(`Could not find <${tagName}> in source file`);
    }
    return match[0];
}

function replaceBlock(html, label, div, markup) {
    const startMarker = `<!-- ${label}:START (generated by build.js from ${div}.html — do not edit here; edit ${div}.html then run \`node build.js\`) -->`;
    const endMarker = `<!-- ${label}:END -->`;
    const block = `${startMarker}\n    ${markup}\n    ${endMarker}`;

    const existingBlockPattern = new RegExp(
        `<!-- ${label}:START[\\s\\S]*?<!-- ${label}:END -->`
    );
    if (existingBlockPattern.test(html)) {
        return html.replace(existingBlockPattern, block);
    }

    const placeholderPattern = new RegExp(
        `(<!--\\s*DYNAMIC ${label}\\s*-->\\s*\\n\\s*)?<div id="${div}"></div>`
    );
    if (!placeholderPattern.test(html)) {
        throw new Error(`Could not find a ${div} placeholder to replace`);
    }
    return html.replace(placeholderPattern, block);
}

function stripInjectionScripts(html) {
    return html
        .replace(/[ \t]*<script src="js\/header\.js"><\/script>\n?/, "")
        .replace(/[ \t]*<script src="js\/footer\.js"><\/script>\n?/, "");
}

function stripStaleLabelComments(html) {
    return html
        .replace(/[ \t]*<!--\s*(?:DYNAMIC\s+)?HEADER\s*-->\s*\n(?=[ \t]*(?:<div id="header">|<!-- HEADER:START))/i, "")
        .replace(/[ \t]*<!--\s*(?:DYNAMIC\s+)?FOOTER\s*-->\s*\n(?=[ \t]*(?:<div id="footer">|<!-- FOOTER:START))/i, "");
}

function collapseBlankLines(html) {
    return html
        .replace(/\n{3,}/g, "\n\n")
        .replace(/(?:[ \t]*\n)+([ \t]*<\/body>)/, "\n$1");
}

const headerSource = fs.readFileSync(path.join(ROOT, "header.html"), "utf8").replace(/\r\n/g, "\n");
const footerSource = fs.readFileSync(path.join(ROOT, "footer.html"), "utf8").replace(/\r\n/g, "\n");
const headerMarkup = extractTag(headerSource, "header");
const footerMarkup = extractTag(footerSource, "footer");

for (const page of PAGES) {
    const filePath = path.join(ROOT, page);
    let html = fs.readFileSync(filePath, "utf8");

    // Normalize to LF so regexes below work regardless of the mix of
    // CRLF/LF line endings this file may currently have on disk.
    html = html.replace(/\r\n/g, "\n");

    html = stripStaleLabelComments(html);
    html = replaceBlock(html, "HEADER", "header", headerMarkup);
    html = replaceBlock(html, "FOOTER", "footer", footerMarkup);
    html = stripInjectionScripts(html);
    html = collapseBlankLines(html);

    fs.writeFileSync(filePath, html, "utf8");
    console.log(`Updated ${page}`);
}

console.log("Build complete.");
